/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123LangChar125RouteRouteImport } from './routes/{-$lang}/route'
import { Route as Char123LangChar125IndexRouteImport } from './routes/{-$lang}/index'
import { Route as Char123LangChar125ContactRouteImport } from './routes/{-$lang}/contact'
import { Route as Char123LangChar125PaymentsRouteImport } from './routes/{-$lang}/payments'
import { Route as Char123LangChar125ProjectsRouteImport } from './routes/{-$lang}/projects'
import { Route as Char123LangChar125ServicesRouteImport } from './routes/{-$lang}/services'
import { Route as Char123LangChar125ServicesIndexRouteImport } from './routes/{-$lang}/services.index'
import { Route as Char123LangChar125ServicesSlugRouteImport } from './routes/{-$lang}/services.$slug'

const Char123LangChar125RouteRoute = Char123LangChar125RouteRouteImport.update({
  id: '/{-$lang}',
  path: '/{-$lang}',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LangChar125IndexRoute = Char123LangChar125IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => Char123LangChar125RouteRoute,
} as any)
const Char123LangChar125ContactRoute =
  Char123LangChar125ContactRouteImport.update({
    id: '/contact',
    path: '/contact',
    getParentRoute: () => Char123LangChar125RouteRoute,
  } as any)
const Char123LangChar125PaymentsRoute =
  Char123LangChar125PaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => Char123LangChar125RouteRoute,
  } as any)
const Char123LangChar125ProjectsRoute =
  Char123LangChar125ProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => Char123LangChar125RouteRoute,
  } as any)
const Char123LangChar125ServicesRoute =
  Char123LangChar125ServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => Char123LangChar125RouteRoute,
  } as any)
const Char123LangChar125ServicesIndexRoute =
  Char123LangChar125ServicesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LangChar125ServicesRoute,
  } as any)
const Char123LangChar125ServicesSlugRoute =
  Char123LangChar125ServicesSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => Char123LangChar125ServicesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/{-$lang}': typeof Char123LangChar125RouteRouteWithChildren
  '/{-$lang}/contact': typeof Char123LangChar125ContactRoute
  '/{-$lang}/payments': typeof Char123LangChar125PaymentsRoute
  '/{-$lang}/projects': typeof Char123LangChar125ProjectsRoute
  '/{-$lang}/services': typeof Char123LangChar125ServicesRouteWithChildren
  '/{-$lang}/': typeof Char123LangChar125IndexRoute
  '/{-$lang}/services/$slug': typeof Char123LangChar125ServicesSlugRoute
  '/{-$lang}/services/': typeof Char123LangChar125ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/{-$lang}/contact': typeof Char123LangChar125ContactRoute
  '/{-$lang}/payments': typeof Char123LangChar125PaymentsRoute
  '/{-$lang}/projects': typeof Char123LangChar125ProjectsRoute
  '/{-$lang}': typeof Char123LangChar125IndexRoute
  '/{-$lang}/services/$slug': typeof Char123LangChar125ServicesSlugRoute
  '/{-$lang}/services': typeof Char123LangChar125ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$lang}': typeof Char123LangChar125RouteRouteWithChildren
  '/{-$lang}/contact': typeof Char123LangChar125ContactRoute
  '/{-$lang}/payments': typeof Char123LangChar125PaymentsRoute
  '/{-$lang}/projects': typeof Char123LangChar125ProjectsRoute
  '/{-$lang}/services': typeof Char123LangChar125ServicesRouteWithChildren
  '/{-$lang}/': typeof Char123LangChar125IndexRoute
  '/{-$lang}/services/$slug': typeof Char123LangChar125ServicesSlugRoute
  '/{-$lang}/services/': typeof Char123LangChar125ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$lang}'
    | '/{-$lang}/contact'
    | '/{-$lang}/payments'
    | '/{-$lang}/projects'
    | '/{-$lang}/services'
    | '/{-$lang}/'
    | '/{-$lang}/services/$slug'
    | '/{-$lang}/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/{-$lang}/contact'
    | '/{-$lang}/payments'
    | '/{-$lang}/projects'
    | '/{-$lang}'
    | '/{-$lang}/services/$slug'
    | '/{-$lang}/services'
  id:
    | '__root__'
    | '/{-$lang}'
    | '/{-$lang}/contact'
    | '/{-$lang}/payments'
    | '/{-$lang}/projects'
    | '/{-$lang}/services'
    | '/{-$lang}/'
    | '/{-$lang}/services/$slug'
    | '/{-$lang}/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123LangChar125RouteRoute: typeof Char123LangChar125RouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{-$lang}': {
      id: '/{-$lang}'
      path: '/{-$lang}'
      fullPath: '/{-$lang}'
      preLoaderRoute: typeof Char123LangChar125RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$lang}/': {
      id: '/{-$lang}/'
      path: '/'
      fullPath: '/{-$lang}/'
      preLoaderRoute: typeof Char123LangChar125IndexRouteImport
      parentRoute: typeof Char123LangChar125RouteRoute
    }
    '/{-$lang}/contact': {
      id: '/{-$lang}/contact'
      path: '/contact'
      fullPath: '/{-$lang}/contact'
      preLoaderRoute: typeof Char123LangChar125ContactRouteImport
      parentRoute: typeof Char123LangChar125RouteRoute
    }
    '/{-$lang}/payments': {
      id: '/{-$lang}/payments'
      path: '/payments'
      fullPath: '/{-$lang}/payments'
      preLoaderRoute: typeof Char123LangChar125PaymentsRouteImport
      parentRoute: typeof Char123LangChar125RouteRoute
    }
    '/{-$lang}/projects': {
      id: '/{-$lang}/projects'
      path: '/projects'
      fullPath: '/{-$lang}/projects'
      preLoaderRoute: typeof Char123LangChar125ProjectsRouteImport
      parentRoute: typeof Char123LangChar125RouteRoute
    }
    '/{-$lang}/services': {
      id: '/{-$lang}/services'
      path: '/services'
      fullPath: '/{-$lang}/services'
      preLoaderRoute: typeof Char123LangChar125ServicesRouteImport
      parentRoute: typeof Char123LangChar125RouteRoute
    }
    '/{-$lang}/services/': {
      id: '/{-$lang}/services/'
      path: '/'
      fullPath: '/{-$lang}/services/'
      preLoaderRoute: typeof Char123LangChar125ServicesIndexRouteImport
      parentRoute: typeof Char123LangChar125ServicesRoute
    }
    '/{-$lang}/services/$slug': {
      id: '/{-$lang}/services/$slug'
      path: '/$slug'
      fullPath: '/{-$lang}/services/$slug'
      preLoaderRoute: typeof Char123LangChar125ServicesSlugRouteImport
      parentRoute: typeof Char123LangChar125ServicesRoute
    }
  }
}

interface Char123LangChar125ServicesRouteChildren {
  Char123LangChar125ServicesSlugRoute: typeof Char123LangChar125ServicesSlugRoute
  Char123LangChar125ServicesIndexRoute: typeof Char123LangChar125ServicesIndexRoute
}

const Char123LangChar125ServicesRouteChildren: Char123LangChar125ServicesRouteChildren =
  {
    Char123LangChar125ServicesSlugRoute: Char123LangChar125ServicesSlugRoute,
    Char123LangChar125ServicesIndexRoute: Char123LangChar125ServicesIndexRoute,
  }

const Char123LangChar125ServicesRouteWithChildren =
  Char123LangChar125ServicesRoute._addFileChildren(
    Char123LangChar125ServicesRouteChildren,
  )

interface Char123LangChar125RouteRouteChildren {
  Char123LangChar125ContactRoute: typeof Char123LangChar125ContactRoute
  Char123LangChar125PaymentsRoute: typeof Char123LangChar125PaymentsRoute
  Char123LangChar125ProjectsRoute: typeof Char123LangChar125ProjectsRoute
  Char123LangChar125ServicesRoute: typeof Char123LangChar125ServicesRouteWithChildren
  Char123LangChar125IndexRoute: typeof Char123LangChar125IndexRoute
}

const Char123LangChar125RouteRouteChildren: Char123LangChar125RouteRouteChildren =
  {
    Char123LangChar125ContactRoute: Char123LangChar125ContactRoute,
    Char123LangChar125PaymentsRoute: Char123LangChar125PaymentsRoute,
    Char123LangChar125ProjectsRoute: Char123LangChar125ProjectsRoute,
    Char123LangChar125ServicesRoute:
      Char123LangChar125ServicesRouteWithChildren,
    Char123LangChar125IndexRoute: Char123LangChar125IndexRoute,
  }

const Char123LangChar125RouteRouteWithChildren =
  Char123LangChar125RouteRoute._addFileChildren(
    Char123LangChar125RouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  Char123LangChar125RouteRoute: Char123LangChar125RouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
